# Generated by Django 4.1.4 on 2022-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_settings', models.BooleanField(default=False)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('site_hero', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_title_hero', models.TextField(blank=True, null=True)),
                ('text_small_hero', models.TextField(blank=True, null=True)),
                ('title_2', models.TextField(blank=True, null=True)),
                ('small_2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
