# Generated by Django 4.1.4 on 2022-12-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_sitesettingtranslation_use_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingtranslation',
            name='use_settings',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
