# Generated by Django 4.1.4 on 2022-12-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_sitesettingtranslation_use_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSetting',
            new_name='IndexPage',
        ),
        migrations.RenameModel(
            old_name='SiteSettingTranslation',
            new_name='IndexPageTranslation',
        ),
        migrations.AlterModelOptions(
            name='indexpagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'index page Translation'},
        ),
        migrations.AlterModelTable(
            name='indexpagetranslation',
            table='settings_indexpage_translation',
        ),
    ]
