# Generated by Django 4.1.4 on 2022-12-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_rename_sitesetting_indexpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagetranslation',
            name='book_now',
            field=models.TextField(blank=True, null=True),
        ),
    ]
