# Generated by Django 4.1.4 on 2022-12-30 07:26

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_indexpagetranslation_book_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Top Nav',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name_plural': 'Index Page'},
        ),
        migrations.RemoveField(
            model_name='indexpagetranslation',
            name='site_logo',
        ),
        migrations.AlterField(
            model_name='indexpagetranslation',
            name='use_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TopNavTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('use_settings', models.BooleanField(default=False)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('home', models.TextField(blank=True, null=True)),
                ('rooms_and_suites', models.TextField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('contact_us', models.TextField(blank=True, null=True)),
                ('book_now', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='settings.topnav')),
            ],
            options={
                'verbose_name': 'top nav Translation',
                'db_table': 'settings_topnav_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
