# Generated by Django 4.1.4 on 2023-01-04 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_topnav_alter_indexpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagetranslation',
            name='first_Of_4_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='first_Of_4_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='fourth_Of_4_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='fourth_Of_4_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='presemtation_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='presentation_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='second_Of_4_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='second_Of_4_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='third_Of_4_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='third_Of_4_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='tick_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='tick_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='tick_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
