# Generated by Django 4.1.4 on 2023-01-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_rename_presemtation_description_indexpagetranslation_presentation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagetranslation',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='image_small1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='image_small2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='image_small3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='image_small4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='indexpagetranslation',
            name='image_small5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
