# Generated by Django 4.1.4 on 2023-01-06 16:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_indexpagetranslation_image_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnavtranslation',
            name='nav_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
