# Generated by Django 4.1.4 on 2022-12-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_aproved',
            field=models.BooleanField(default=False),
        ),
    ]
